### ISSUE TITLE
Add months

### ISSUE THREAD

**Issue by olegof2020** [jlattimer/CRM-DateTime-Workflow-Utilities#33]
Hello,
What is the calculation formula for add months ?
I checked adding one month for every 1 day of each month and got different results.
Here the results I got:
For months 01,02,04,06,08,09,11 - the result is the the first day of next month (1/1/2020 - 1/2/2020 ...)
for other months here the results:
1/3/2020 - 30/03/2020
1/5/2020 - 31/05/2020
1/7/2020 - 31/07/2020
1/10/2020 - 30/10/2020
1/12/2020 - 31/12/2020

Thanks,

**Comment by jlattimer** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.datetime.addmonths?view=netframework-4.8

No conversations are happening, it's taking the input as a date and using the .NET method to add the specified number of months. 

Just tested again and it's still working as expected. This code hasn't changed in years and nobody else has ever brought this up so I'm pretty sure the issue is on your side somewhere.

**Comment by olegof2020** [comment]
I think I found the problem.
If I use the workflow at Pacific time zone it works fine.
if I use it at Jerusalem time zone it works wrong, for example adding 1 moth for 1 March returns 30 March and not 1 April.
For the contrary, .Net functions works fine for both timezones.
Is the workflow built to be used only in specific time zone ?


![image](https://user-images.githubusercontent.com/59932763/79068307-b3362a00-7cce-11ea-8993-7f895eaaaef8.png)
![image](https://user-images.githubusercontent.com/59932763/79068355-027c5a80-7ccf-11ea-9230-a20c7839d7bc.png)
